[package]
name = "agent-smith"
version = "0.1.0"
edition = "2021"
description = "An experimental high-level bot framework for the Matrix SDK"
license = "Apache-2.0"
homepage = "https://github.com/matrix-org/matrix-rust-sdk"

